<a href="https://colab.research.google.com/github/TacHyoNic900/Hello_World/blob/master/ai5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sklearn
import pandas as pd

In [2]:
from sklearn.datasets import load_iris
iris=load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
df=pd.DataFrame(iris['data'])
print(df)
print(iris['target_names'])
iris['feature_names']

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
['setosa' 'versicolor' 'virginica']


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
x=df
y=iris['target']

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [7]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
import numpy as np
x_new=np.array([[5,2.9,1,0.2]])

In [9]:
prediction=knn.predict(x_new)
iris['target_names'][prediction]

array(['setosa'], dtype='<U10')

In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [11]:
y_pred=knn.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("correct prediction",accuracy_score(y_test,y_pred))
print("wrong prediction",(1-accuracy_score(y_test,y_pred)))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
correct prediction 0.98
wrong prediction 0.020000000000000018
